const bcrypt = require('bcryptjs');
const { pool, initDB } = require('./init');

const seed = async () => {
  try {
    await initDB();
    const client = await pool.connect();

    // Clear existing data
    await client.query(`
      TRUNCATE users, security_alerts, travelers, trips, destinations, incident_reports,
      emergency_contacts, travel_advisories, risk_assessments, threat_analyses,
      communication_templates, geofencing_zones RESTART IDENTITY CASCADE;
    `);

    // Seed Users
    const hashedPassword = await bcrypt.hash('Admin123!', 10);
    await client.query(`
      INSERT INTO users (email, password, name, role) VALUES
      ('admin@travelsecurity.com', $1, 'Admin User', 'admin'),
      ('operator@travelsecurity.com', $1, 'John Operator', 'operator'),
      ('manager@travelsecurity.com', $1, 'Sarah Manager', 'manager');
    `, [hashedPassword]);

    // Seed Security Alerts (15+)
    await client.query(`
      INSERT INTO security_alerts (title, description, severity, category, region, country, city, source, status, affected_travelers, latitude, longitude) VALUES
      ('Terrorist Attack Warning - Paris Metro', 'Intelligence suggests potential attack on Paris metro system. Heightened security presence recommended.', 'critical', 'Terrorism', 'Europe', 'France', 'Paris', 'French Intelligence Agency', 'active', 45, 48.8566, 2.3522),
      ('Political Unrest in Bangkok', 'Large-scale protests expected in central Bangkok near government buildings. Potential for violence.', 'high', 'Political Unrest', 'Southeast Asia', 'Thailand', 'Bangkok', 'US Embassy Bangkok', 'active', 23, 13.7563, 100.5018),
      ('Hurricane Warning - Caribbean', 'Category 4 hurricane approaching Jamaica and Haiti. Evacuation orders issued for coastal areas.', 'critical', 'Natural Disaster', 'Caribbean', 'Jamaica', 'Kingston', 'NOAA Weather Service', 'active', 67, 18.1096, -77.2975),
      ('Kidnapping Risk - Mexico City', 'Increased kidnapping incidents targeting tourists in specific neighborhoods of Mexico City.', 'high', 'Crime', 'Central America', 'Mexico', 'Mexico City', 'Local Security Forces', 'monitoring', 34, 19.4326, -99.1332),
      ('Ebola Outbreak - DRC', 'New Ebola cases confirmed in eastern Congo. WHO has raised alert level. Avoid non-essential travel.', 'critical', 'Health', 'Africa', 'DR Congo', 'Goma', 'WHO', 'active', 8, -1.6585, 29.2200),
      ('Volcanic Eruption - Bali', 'Mount Agung showing increased activity. Airport closures possible. Exclusion zone expanded to 10km.', 'high', 'Natural Disaster', 'Southeast Asia', 'Indonesia', 'Bali', 'Indonesian Geological Agency', 'monitoring', 89, -8.3431, 115.5070),
      ('Civil War Escalation - Sudan', 'Fighting intensified between military factions. All foreign nationals advised to evacuate immediately.', 'critical', 'Armed Conflict', 'Africa', 'Sudan', 'Khartoum', 'UN Security Council', 'active', 12, 15.5007, 32.5599),
      ('Cyber Attack on Airport Systems - Frankfurt', 'Major cyber attack disrupting flight operations at Frankfurt Airport. Delays expected for 48 hours.', 'medium', 'Cyber', 'Europe', 'Germany', 'Frankfurt', 'Europol', 'active', 156, 50.1109, 8.6821),
      ('Monsoon Flooding - Mumbai', 'Severe monsoon flooding across Mumbai. Transportation paralyzed. Multiple casualties reported.', 'high', 'Natural Disaster', 'South Asia', 'India', 'Mumbai', 'Indian Meteorological Dept', 'active', 42, 19.0760, 72.8777),
      ('Border Closure - Israel-Lebanon', 'Complete border closure between Israel and Lebanon due to military operations. No crossing permitted.', 'high', 'Military', 'Middle East', 'Israel', 'Northern Border', 'Israeli Defense Forces', 'active', 18, 33.2774, 35.2043),
      ('Mass Shooting - Las Vegas', 'Active shooter situation near Las Vegas Strip. Area locked down. Avoid the vicinity.', 'critical', 'Terrorism', 'North America', 'United States', 'Las Vegas', 'FBI', 'resolved', 28, 36.1699, -115.1398),
      ('Tsunami Warning - Japan', 'Earthquake magnitude 7.2 off coast of Japan. Tsunami warning issued for Pacific coast regions.', 'critical', 'Natural Disaster', 'East Asia', 'Japan', 'Tokyo', 'Japan Meteorological Agency', 'monitoring', 203, 35.6762, 139.6503),
      ('Drug Cartel Violence - Cancun', 'Escalating cartel violence near tourist zones in Cancun. Several resorts on heightened alert.', 'medium', 'Crime', 'Central America', 'Mexico', 'Cancun', 'Mexican Federal Police', 'active', 145, 21.1619, -86.8515),
      ('Wildfire Emergency - Australia', 'Massive wildfires threatening Sydney suburbs. Air quality hazardous. Evacuation orders in effect.', 'high', 'Natural Disaster', 'Oceania', 'Australia', 'Sydney', 'NSW Fire Service', 'active', 76, -33.8688, 151.2093),
      ('Diplomatic Crisis - Turkey', 'Diplomatic tensions rising. Embassy operations suspended. Visa processing halted indefinitely.', 'medium', 'Political', 'Middle East', 'Turkey', 'Ankara', 'State Department', 'monitoring', 31, 39.9334, 32.8597),
      ('Train Derailment - Italy', 'High-speed train derailment near Florence. Rail services suspended across region. Multiple injuries.', 'medium', 'Transportation', 'Europe', 'Italy', 'Florence', 'Italian Rail Authority', 'active', 19, 43.7696, 11.2558),
      ('Cholera Outbreak - Haiti', 'Cholera outbreak in Port-au-Prince following flooding. Contaminated water sources identified.', 'high', 'Health', 'Caribbean', 'Haiti', 'Port-au-Prince', 'WHO', 'active', 5, 18.5944, -72.3074)
    `);

    // Seed Travelers (15+)
    await client.query(`
      INSERT INTO travelers (first_name, last_name, email, phone, passport_number, nationality, emergency_contact_name, emergency_contact_phone, current_location, status, risk_level) VALUES
      ('Emma', 'Johnson', 'emma.j@email.com', '+1-555-0101', 'US12345678', 'American', 'Robert Johnson', '+1-555-0102', 'Paris, France', 'traveling', 'high'),
      ('James', 'Williams', 'james.w@email.com', '+44-20-5550103', 'GB87654321', 'British', 'Mary Williams', '+44-20-5550104', 'Bangkok, Thailand', 'alert', 'high'),
      ('Sofia', 'Garcia', 'sofia.g@email.com', '+34-555-0105', 'ES11223344', 'Spanish', 'Carlos Garcia', '+34-555-0106', 'Tokyo, Japan', 'traveling', 'medium'),
      ('Marco', 'Rossi', 'marco.r@email.com', '+39-555-0107', 'IT55667788', 'Italian', 'Anna Rossi', '+39-555-0108', 'Bali, Indonesia', 'alert', 'high'),
      ('Yuki', 'Tanaka', 'yuki.t@email.com', '+81-555-0109', 'JP99001122', 'Japanese', 'Hiro Tanaka', '+81-555-0110', 'Sydney, Australia', 'traveling', 'medium'),
      ('Anna', 'Mueller', 'anna.m@email.com', '+49-555-0111', 'DE33445566', 'German', 'Klaus Mueller', '+49-555-0112', 'Mumbai, India', 'alert', 'high'),
      ('Chen', 'Wei', 'chen.w@email.com', '+86-555-0113', 'CN77889900', 'Chinese', 'Li Wei', '+86-555-0114', 'London, UK', 'active', 'low'),
      ('Maria', 'Santos', 'maria.s@email.com', '+55-555-0115', 'BR11224433', 'Brazilian', 'Jose Santos', '+55-555-0116', 'Cancun, Mexico', 'traveling', 'medium'),
      ('Pierre', 'Dubois', 'pierre.d@email.com', '+33-555-0117', 'FR55668877', 'French', 'Claire Dubois', '+33-555-0118', 'New York, USA', 'active', 'low'),
      ('Olga', 'Petrov', 'olga.p@email.com', '+7-555-0119', 'RU99007766', 'Russian', 'Ivan Petrov', '+7-555-0120', 'Istanbul, Turkey', 'traveling', 'medium'),
      ('Ahmed', 'Hassan', 'ahmed.h@email.com', '+20-555-0121', 'EG12349876', 'Egyptian', 'Fatima Hassan', '+20-555-0122', 'Dubai, UAE', 'active', 'low'),
      ('Sarah', 'Anderson', 'sarah.a@email.com', '+1-555-0123', 'US98761234', 'American', 'Tom Anderson', '+1-555-0124', 'Kingston, Jamaica', 'alert', 'critical'),
      ('Hans', 'Schmidt', 'hans.s@email.com', '+49-555-0125', 'DE56781234', 'German', 'Greta Schmidt', '+49-555-0126', 'Frankfurt, Germany', 'traveling', 'low'),
      ('Aisha', 'Patel', 'aisha.p@email.com', '+91-555-0127', 'IN43218765', 'Indian', 'Raj Patel', '+91-555-0128', 'Singapore', 'active', 'low'),
      ('Lucas', 'Fernandez', 'lucas.f@email.com', '+54-555-0129', 'AR87651234', 'Argentine', 'Rosa Fernandez', '+54-555-0130', 'Mexico City, Mexico', 'alert', 'high'),
      ('Kim', 'Soo-Yeon', 'kim.sy@email.com', '+82-555-0131', 'KR12348765', 'South Korean', 'Park Soo-Yeon', '+82-555-0132', 'Florence, Italy', 'traveling', 'medium')
    `);

    // Seed Trips (15+)
    await client.query(`
      INSERT INTO trips (traveler_id, destination, country, start_date, end_date, status, hotel_name, hotel_address, flight_number, notes, risk_level) VALUES
      (1, 'Paris', 'France', '2026-03-10', '2026-03-20', 'active', 'Hotel Le Marais', '12 Rue de Rivoli, Paris', 'AF1234', 'Business conference attendee', 'high'),
      (2, 'Bangkok', 'Thailand', '2026-03-05', '2026-03-25', 'active', 'Mandarin Oriental', '48 Oriental Ave, Bangkok', 'BA5678', 'Leisure travel with family', 'high'),
      (3, 'Tokyo', 'Japan', '2026-03-12', '2026-03-22', 'active', 'Park Hyatt Tokyo', '3-7-1 Nishi Shinjuku', 'IB9012', 'Cultural tour group leader', 'medium'),
      (4, 'Bali', 'Indonesia', '2026-03-01', '2026-03-15', 'active', 'Four Seasons Bali', 'Jimbaran Bay, Bali', 'AZ3456', 'Honeymoon trip', 'high'),
      (5, 'Sydney', 'Australia', '2026-03-08', '2026-03-18', 'active', 'Sydney Harbour Hotel', '55 George St, Sydney', 'JL7890', 'Academic conference', 'medium'),
      (6, 'Mumbai', 'India', '2026-03-15', '2026-03-28', 'active', 'Taj Mahal Palace', 'Apollo Bunder, Mumbai', 'LH2345', 'NGO volunteer work', 'high'),
      (7, 'London', 'United Kingdom', '2026-03-20', '2026-04-05', 'upcoming', 'The Savoy', 'Strand, London', 'CA6789', 'Extended business trip', 'low'),
      (8, 'Cancun', 'Mexico', '2026-03-10', '2026-03-17', 'active', 'Ritz-Carlton Cancun', 'Retorno del Rey 36', 'LA0123', 'Vacation with friends', 'medium'),
      (9, 'New York', 'United States', '2026-02-28', '2026-03-14', 'active', 'The Plaza Hotel', '768 5th Ave, New York', 'AF4567', 'Art exhibition curator', 'low'),
      (10, 'Istanbul', 'Turkey', '2026-03-18', '2026-03-30', 'upcoming', 'Ciragan Palace', 'Ciragan Cad 32, Istanbul', 'TK8901', 'Historical research', 'medium'),
      (11, 'Dubai', 'UAE', '2026-03-22', '2026-04-02', 'upcoming', 'Burj Al Arab', 'Jumeirah St, Dubai', 'EK2345', 'Business meetings', 'low'),
      (12, 'Kingston', 'Jamaica', '2026-03-08', '2026-03-15', 'active', 'Half Moon Resort', 'Rose Hall, Montego Bay', 'AA6789', 'Volunteer mission', 'critical'),
      (13, 'Frankfurt', 'Germany', '2026-03-12', '2026-03-16', 'active', 'Steigenberger Hotel', 'Am Kaiserplatz, Frankfurt', 'LH0123', 'Tech summit speaker', 'low'),
      (14, 'Singapore', 'Singapore', '2026-03-20', '2026-04-01', 'upcoming', 'Marina Bay Sands', '10 Bayfront Ave', 'SQ4567', 'Medical conference', 'low'),
      (15, 'Mexico City', 'Mexico', '2026-03-05', '2026-03-20', 'active', 'Four Seasons CDMX', 'Paseo de la Reforma 500', 'AM8901', 'Documentary filming', 'high'),
      (16, 'Florence', 'Italy', '2026-03-14', '2026-03-24', 'active', 'Hotel Brunelleschi', 'Piazza S. Elisabetta 3', 'KE2345', 'Art history study', 'medium')
    `);

    // Seed Destinations (15+)
    await client.query(`
      INSERT INTO destinations (name, country, region, risk_level, risk_score, description, travel_advisory, health_risks, entry_requirements, local_emergency_number, active_alerts, active_travelers) VALUES
      ('Paris', 'France', 'Western Europe', 'high', 72, 'Major European capital with heightened security concerns', 'Exercise increased caution due to terrorism threat', 'Standard European health infrastructure', 'Valid passport, Schengen visa if applicable', '112', 2, 45),
      ('Bangkok', 'Thailand', 'Southeast Asia', 'high', 68, 'Popular tourist destination with ongoing political instability', 'Reconsider travel to protest areas', 'Dengue fever risk, avoid tap water', 'Visa on arrival for most nationalities', '191', 1, 23),
      ('Tokyo', 'Japan', 'East Asia', 'medium', 35, 'Generally safe with earthquake/tsunami risks', 'Exercise normal precautions', 'High healthcare standards', 'Visa-free for many nationalities up to 90 days', '110', 1, 15),
      ('Bali', 'Indonesia', 'Southeast Asia', 'high', 65, 'Tourist island with volcanic activity risks', 'Exercise increased caution', 'Rabies risk, tropical diseases', 'Visa on arrival or visa-free for 30 days', '112', 1, 89),
      ('Sydney', 'Australia', 'Oceania', 'medium', 42, 'Generally safe with bushfire and extreme weather risks', 'Exercise normal precautions', 'Sun protection essential, wildlife hazards', 'ETA or visa required', '000', 1, 76),
      ('Mumbai', 'India', 'South Asia', 'high', 62, 'Major city with monsoon flooding and infrastructure challenges', 'Exercise increased caution', 'Waterborne diseases, air quality issues', 'E-visa available for most nationalities', '112', 1, 42),
      ('Kingston', 'Jamaica', 'Caribbean', 'critical', 85, 'Hurricane-prone region with high crime rates', 'Reconsider travel due to crime and natural disasters', 'Zika virus, dengue fever risk', 'Visa-free for most Western nationalities', '119', 1, 67),
      ('Mexico City', 'Mexico', 'Central America', 'high', 70, 'Major city with kidnapping and cartel violence risks', 'Exercise increased caution', 'Altitude sickness, air pollution', 'Visa-free for tourism up to 180 days', '911', 1, 34),
      ('Istanbul', 'Turkey', 'Middle East/Europe', 'medium', 55, 'Transcontinental city with political tensions', 'Exercise increased caution', 'Standard health precautions', 'E-visa required for most nationalities', '112', 1, 31),
      ('Dubai', 'UAE', 'Middle East', 'low', 20, 'Generally very safe with strict laws', 'Exercise normal precautions', 'Heat-related illness risk', 'Visa on arrival for many nationalities', '999', 0, 15),
      ('Frankfurt', 'Germany', 'Western Europe', 'low', 25, 'Major financial hub with standard European safety', 'Exercise normal precautions', 'High healthcare standards', 'Valid passport, Schengen visa if applicable', '112', 1, 156),
      ('Singapore', 'Singapore', 'Southeast Asia', 'low', 15, 'One of the safest cities globally with strict laws', 'Exercise normal precautions', 'Dengue fever risk, excellent healthcare', 'Visa-free for most nationalities', '999', 0, 12),
      ('Cancun', 'Mexico', 'Central America', 'medium', 58, 'Popular resort destination with nearby cartel activity', 'Exercise increased caution outside resort zones', 'Waterborne diseases, sunburn risk', 'Tourist card required', '911', 1, 145),
      ('Khartoum', 'Sudan', 'East Africa', 'critical', 95, 'Active civil war zone with extreme danger', 'Do not travel - armed conflict', 'Limited medical facilities, multiple disease risks', 'Visa required, extremely difficult to obtain', '999', 1, 12),
      ('Florence', 'Italy', 'Western Europe', 'low', 22, 'Historic city with standard European safety profile', 'Exercise normal precautions', 'High healthcare standards', 'Valid passport, Schengen visa if applicable', '112', 1, 19),
      ('Port-au-Prince', 'Haiti', 'Caribbean', 'critical', 92, 'Extreme crime, political instability, health emergencies', 'Do not travel', 'Cholera, limited medical care', 'Passport required, no visa for short stays', '114', 1, 5)
    `);

    // Seed Incident Reports (15+)
    await client.query(`
      INSERT INTO incident_reports (title, description, incident_type, severity, location, country, date_occurred, reported_by, status, affected_travelers_count, response_actions) VALUES
      ('Tourist Bus Robbery in Mexico City', 'Armed robbery of a tourist bus in Tepito neighborhood. 3 travelers injured, valuables stolen.', 'Crime', 'high', 'Mexico City', 'Mexico', '2026-03-10 14:30:00', 'Local Police', 'investigating', 12, 'Contacted embassy, medical assistance provided'),
      ('Hotel Fire in Bangkok', 'Fire broke out on 5th floor of tourist hotel. All guests evacuated safely.', 'Fire', 'medium', 'Bangkok', 'Thailand', '2026-03-09 02:15:00', 'Hotel Management', 'resolved', 8, 'Relocated travelers to partner hotel'),
      ('Traveler Medical Emergency - Bali', 'Tourist suffered severe allergic reaction. Required emergency airlift to Singapore hospital.', 'Medical', 'high', 'Bali', 'Indonesia', '2026-03-11 18:45:00', 'Tour Guide', 'resolved', 1, 'Insurance company contacted, family notified'),
      ('Passport Theft Ring - Paris', 'Organized gang targeting tourists at Eiffel Tower area. Multiple passports stolen.', 'Crime', 'medium', 'Paris', 'France', '2026-03-08 11:00:00', 'French Police', 'investigating', 6, 'Emergency travel documents arranged'),
      ('Earthquake Damage - Tokyo', 'Magnitude 5.8 earthquake caused minor damage to hotel infrastructure. No injuries.', 'Natural Disaster', 'medium', 'Tokyo', 'Japan', '2026-03-12 03:22:00', 'Hotel Management', 'resolved', 15, 'Building inspection completed, all clear'),
      ('Traveler Detained - Istanbul', 'British national detained at airport for alleged customs violation. Consular access requested.', 'Legal', 'high', 'Istanbul', 'Turkey', '2026-03-13 09:30:00', 'British Consulate', 'investigating', 1, 'Legal representation arranged'),
      ('Flash Flooding - Mumbai', 'Sudden flooding stranded 12 travelers in hotel. Roads impassable for 36 hours.', 'Natural Disaster', 'high', 'Mumbai', 'India', '2026-03-14 16:00:00', 'Operations Center', 'open', 12, 'Emergency supplies delivered, evacuation planned'),
      ('Food Poisoning Outbreak - Cancun', 'Multiple travelers from same resort reported severe food poisoning symptoms.', 'Health', 'medium', 'Cancun', 'Mexico', '2026-03-07 20:00:00', 'Resort Management', 'investigating', 23, 'Health authorities notified, medical treatment provided'),
      ('Lost Traveler Group - Khartoum', 'Communication lost with group of 4 aid workers. Last known location near conflict zone.', 'Missing Persons', 'critical', 'Khartoum', 'Sudan', '2026-03-06 08:00:00', 'NGO Coordinator', 'open', 4, 'Military liaison contacted, search operation initiated'),
      ('Scuba Diving Accident - Bali', 'Tourist experienced decompression sickness during diving excursion. Hospitalized.', 'Medical', 'high', 'Bali', 'Indonesia', '2026-03-10 10:30:00', 'Dive Operator', 'resolved', 1, 'Hyperbaric treatment provided, insurance claim filed'),
      ('Anti-Tourist Protest - Barcelona', 'Large protest blocking access to tourist areas. Several travelers harassed.', 'Political', 'medium', 'Barcelona', 'Spain', '2026-03-11 15:00:00', 'Spanish Police', 'resolved', 34, 'Alternative routes provided, security escort arranged'),
      ('Volcanic Ash Flight Cancellation', 'Mount Agung eruption caused cancellation of 45 flights. 200+ travelers stranded.', 'Natural Disaster', 'high', 'Bali', 'Indonesia', '2026-03-09 06:00:00', 'Airport Authority', 'investigating', 89, 'Alternative transportation being arranged'),
      ('Cyber Fraud - Frankfurt Airport', 'Fake WiFi hotspot at airport used to steal credit card info from travelers.', 'Cyber', 'medium', 'Frankfurt', 'Germany', '2026-03-12 12:00:00', 'Airport Security', 'investigating', 45, 'Banks notified, affected travelers contacted'),
      ('Vehicle Accident - Safari Kenya', 'Safari vehicle rollover injured 3 tourists. One with serious injuries airlifted.', 'Transportation', 'high', 'Nairobi', 'Kenya', '2026-03-08 09:45:00', 'Safari Company', 'resolved', 6, 'Medical evacuation completed, investigation ongoing'),
      ('Traveler Hospitalized - COVID Complications', 'Elderly traveler hospitalized in Singapore with severe respiratory complications.', 'Health', 'high', 'Singapore', 'Singapore', '2026-03-13 14:00:00', 'Hospital Staff', 'open', 1, 'Family contacted, insurance processing')
    `);

    // Seed Emergency Contacts (15+)
    await client.query(`
      INSERT INTO emergency_contacts (name, organization, role, country, region, phone, email, contact_type, available_24h, languages, notes, priority) VALUES
      ('US Embassy Paris', 'US Department of State', 'Consular Services', 'France', 'Europe', '+33-1-4312-2222', 'parisacs@state.gov', 'embassy', true, 'English, French', 'Primary contact for US citizens in France', 1),
      ('Bangkok Hospital', 'Bangkok International Hospital', 'Emergency Department', 'Thailand', 'Southeast Asia', '+66-2-310-3000', 'emergency@bih.co.th', 'hospital', true, 'English, Thai', 'Best English-speaking hospital in Bangkok', 2),
      ('Tokyo Metropolitan Police', 'Tokyo Police Department', 'Foreign Affairs Division', 'Japan', 'East Asia', '+81-3-3501-0110', 'foreign@keishicho.metro.tokyo.jp', 'police', true, 'English, Japanese', 'Dedicated foreign visitor assistance', 3),
      ('Bali International SOS', 'International SOS', 'Medical Evacuation', 'Indonesia', 'Southeast Asia', '+62-361-710505', 'bali@internationalsos.com', 'hospital', true, 'English, Indonesian', 'Primary medical evacuation provider', 1),
      ('Australian Federal Police', 'AFP', 'Counter-Terrorism', 'Australia', 'Oceania', '+61-2-6131-3000', 'afp@afp.gov.au', 'police', true, 'English', 'National security and terrorism response', 2),
      ('Mumbai Fire Brigade', 'BMC Fire Services', 'Emergency Response', 'India', 'South Asia', '+91-22-2307-2727', 'fire@mcgm.gov.in', 'fire', true, 'English, Hindi, Marathi', 'Flood rescue capabilities', 3),
      ('British High Commission Kingston', 'UK Foreign Office', 'Consular Assistance', 'Jamaica', 'Caribbean', '+1-876-936-0700', 'kingston@fco.gov.uk', 'embassy', true, 'English', 'Handles UK and Commonwealth citizen emergencies', 1),
      ('Mexico City Tourist Police', 'Secretaría de Seguridad', 'Tourist Protection', 'Mexico', 'Central America', '+52-55-5250-8221', 'turista@ssp.cdmx.gob.mx', 'police', true, 'English, Spanish', 'Specialized tourist crime unit', 2),
      ('Istanbul Emergency Medicine', 'American Hospital Istanbul', 'Emergency Department', 'Turkey', 'Middle East', '+90-212-444-3777', 'emergency@amerikanhastanesi.org', 'hospital', true, 'English, Turkish', 'Best trauma center for tourists', 2),
      ('Dubai Police Tourist Security', 'Dubai Police', 'Tourist Security Department', 'UAE', 'Middle East', '+971-4-609-6999', 'tourist@dubaipolice.gov.ae', 'police', true, 'English, Arabic', '24/7 tourist assistance', 1),
      ('German Federal Police', 'Bundespolizei', 'Airport Security', 'Germany', 'Europe', '+49-69-690-30400', 'frankfurt@bundespolizei.de', 'police', true, 'English, German', 'Frankfurt airport security operations', 3),
      ('Singapore General Hospital', 'SGH Emergency', 'Emergency Department', 'Singapore', 'Southeast Asia', '+65-6222-3322', 'emergency@sgh.com.sg', 'hospital', true, 'English, Mandarin, Malay', 'Level 1 trauma center', 1),
      ('Global Rescue Operations', 'Global Rescue LLC', 'Field Rescue', 'United States', 'Global', '+1-617-459-4200', 'ops@globalrescue.com', 'other', true, 'English', 'Military-grade rescue and evacuation worldwide', 1),
      ('Travel Guard Insurance', 'AIG Travel', 'Claims & Assistance', 'United States', 'Global', '+1-800-826-1300', 'assistance@travelguard.com', 'insurance', true, 'English, Spanish, French', 'Primary travel insurance provider', 2),
      ('Red Cross International', 'ICRC', 'Humanitarian Aid', 'Switzerland', 'Global', '+41-22-734-6001', 'helpdesk@icrc.org', 'other', true, 'English, French, Arabic, Spanish', 'Conflict zone assistance and family tracing', 1),
      ('Kenya Tourism Police', 'Kenya Police Service', 'Tourist Protection Unit', 'Kenya', 'East Africa', '+254-20-272-2722', 'tourism@kenyapolice.go.ke', 'police', true, 'English, Swahili', 'Safari area security patrols', 2)
    `);

    // Seed Travel Advisories (15+)
    await client.query(`
      INSERT INTO travel_advisories (title, country, region, advisory_level, issued_by, issued_date, expiry_date, description, key_risks, recommendations, status) VALUES
      ('France - Terrorism Threat', 'France', 'Europe', 'exercise_caution', 'US State Department', '2026-03-01', '2026-06-01', 'Elevated terrorism threat across France following intelligence reports.', 'Terrorism, civil unrest, petty crime', 'Avoid crowded public spaces, monitor local news, register with embassy', 'active'),
      ('Thailand - Political Instability', 'Thailand', 'Southeast Asia', 'exercise_caution', 'UK Foreign Office', '2026-02-15', '2026-05-15', 'Ongoing political protests may turn violent without warning.', 'Political violence, martial law possibility', 'Avoid protest areas, carry ID at all times, know embassy location', 'active'),
      ('Sudan - Armed Conflict', 'Sudan', 'Africa', 'do_not_travel', 'US State Department', '2026-01-01', '2026-12-31', 'Active civil war between military factions. Extreme danger to all travelers.', 'Armed conflict, kidnapping, terrorism, crime', 'Depart immediately if possible, shelter in place if not, contact embassy', 'active'),
      ('Haiti - Crime and Health', 'Haiti', 'Caribbean', 'do_not_travel', 'Canadian Government', '2026-02-01', '2026-08-01', 'Extreme crime, gang violence, and cholera outbreak make travel extremely dangerous.', 'Kidnapping, gang violence, cholera, limited medical care', 'Avoid all travel, if present seek immediate evacuation', 'active'),
      ('Mexico - Crime and Kidnapping', 'Mexico', 'Central America', 'reconsider', 'US State Department', '2026-03-01', '2026-09-01', 'Increased cartel violence and kidnapping targeting tourists in multiple states.', 'Kidnapping, cartel violence, petty crime', 'Stay in tourist zones, use registered taxis, avoid traveling at night', 'active'),
      ('Indonesia - Volcanic Activity', 'Indonesia', 'Southeast Asia', 'exercise_caution', 'Australian Government', '2026-03-05', '2026-06-05', 'Multiple volcanoes showing increased activity. Flight disruptions possible.', 'Volcanic eruption, earthquake, tsunami', 'Monitor volcanic alerts, have evacuation plan, carry masks', 'active'),
      ('India - Monsoon Season', 'India', 'South Asia', 'exercise_caution', 'UK Foreign Office', '2026-03-01', '2026-10-01', 'Monsoon season bringing severe flooding and infrastructure disruption.', 'Flooding, infrastructure damage, waterborne diseases', 'Avoid flood-prone areas, carry water purification, have evacuation plan', 'active'),
      ('Turkey - Security Concerns', 'Turkey', 'Middle East', 'exercise_caution', 'US State Department', '2026-02-20', '2026-08-20', 'Diplomatic tensions and border security concerns near Syria border.', 'Terrorism, detention of foreign nationals, border conflicts', 'Avoid border areas, carry passport at all times, register with embassy', 'active'),
      ('Japan - Natural Disaster Preparedness', 'Japan', 'East Asia', 'normal', 'Australian Government', '2026-01-15', '2026-07-15', 'Japan is generally safe but prone to earthquakes, typhoons, and tsunamis.', 'Earthquake, tsunami, typhoon', 'Know evacuation routes, follow J-Alert system, carry emergency kit', 'active'),
      ('Jamaica - Hurricane Season', 'Jamaica', 'Caribbean', 'reconsider', 'US State Department', '2026-03-10', '2026-11-30', 'Hurricane season approaching with above-average activity predicted.', 'Hurricanes, flooding, crime', 'Purchase comprehensive insurance, know shelter locations, monitor weather', 'active'),
      ('Australia - Wildfire Risk', 'Australia', 'Oceania', 'exercise_caution', 'UK Foreign Office', '2026-03-01', '2026-05-01', 'Extreme fire danger in multiple states. Air quality significantly degraded.', 'Wildfire, extreme heat, air quality', 'Monitor fire warnings, carry P2 masks, know evacuation routes', 'active'),
      ('Israel - Military Operations', 'Israel', 'Middle East', 'reconsider', 'US State Department', '2026-02-01', '2026-08-01', 'Ongoing military operations near northern and southern borders.', 'Military conflict, rocket attacks, terrorism', 'Avoid border areas, know bomb shelter locations, monitor alerts', 'active'),
      ('DR Congo - Ebola Outbreak', 'DR Congo', 'Africa', 'do_not_travel', 'WHO / US State Department', '2026-03-01', '2026-09-01', 'Active Ebola outbreak in eastern regions. Limited medical infrastructure.', 'Ebola virus, armed conflict, kidnapping', 'Avoid all travel, if exposed seek immediate medical attention', 'active'),
      ('Germany - Standard Precautions', 'Germany', 'Europe', 'normal', 'US State Department', '2026-01-01', '2026-12-31', 'Germany maintains high safety standards. Cyber security awareness recommended.', 'Petty crime, cyber fraud', 'Use official WiFi only, be aware of surroundings at transit hubs', 'active'),
      ('Singapore - Safe Destination', 'Singapore', 'Southeast Asia', 'normal', 'US State Department', '2026-01-01', '2026-12-31', 'One of the safest countries globally. Strict laws must be respected.', 'Drug trafficking penalties, strict laws', 'Respect local laws, avoid chewing gum in public, no jaywalking', 'active'),
      ('Kenya - Tourism Safety', 'Kenya', 'Africa', 'exercise_caution', 'UK Foreign Office', '2026-02-15', '2026-08-15', 'Safari tourism generally safe but border areas and Nairobi have crime risks.', 'Terrorism, crime, wildlife hazards', 'Use registered tour operators, avoid Somali border, stay in groups', 'active')
    `);

    // Seed Risk Assessments (15+)
    await client.query(`
      INSERT INTO risk_assessments (destination, country, assessment_date, overall_risk, political_risk, terrorism_risk, crime_risk, health_risk, natural_disaster_risk, infrastructure_risk, risk_score, summary, recommendations, assessed_by) VALUES
      ('Paris', 'France', '2026-03-15', 'high', 'medium', 'high', 'medium', 'low', 'low', 'low', 72, 'Elevated terrorism threat with recent intelligence warnings. Petty crime common in tourist areas.', 'Implement buddy system, avoid large gatherings, register with embassy, carry emergency contact card', 'Security Team Alpha'),
      ('Bangkok', 'Thailand', '2026-03-14', 'high', 'high', 'medium', 'medium', 'medium', 'medium', 'medium', 68, 'Political instability creating unpredictable security environment. Protests can escalate rapidly.', 'Avoid government buildings, monitor local news, maintain flexible itinerary, keep passport copies', 'Security Team Beta'),
      ('Tokyo', 'Japan', '2026-03-13', 'medium', 'low', 'low', 'low', 'low', 'high', 'low', 35, 'Excellent security infrastructure but significant natural disaster risk from earthquakes and tsunamis.', 'Download disaster alert apps, know evacuation routes, carry emergency supplies, register with embassy', 'Security Team Alpha'),
      ('Bali', 'Indonesia', '2026-03-12', 'high', 'low', 'medium', 'medium', 'medium', 'high', 'medium', 65, 'Active volcanic threats combined with health risks. Tourist infrastructure adequate but medical facilities limited.', 'Avoid volcano exclusion zones, carry comprehensive insurance, have evacuation plan, carry medical supplies', 'Security Team Gamma'),
      ('Sydney', 'Australia', '2026-03-11', 'medium', 'low', 'low', 'low', 'low', 'high', 'low', 42, 'Currently elevated risk due to wildfire season. Air quality may affect travelers with respiratory conditions.', 'Monitor fire danger ratings, carry P2 masks, know bushfire survival plan, stay hydrated', 'Security Team Alpha'),
      ('Mumbai', 'India', '2026-03-10', 'high', 'medium', 'medium', 'medium', 'high', 'high', 'high', 62, 'Monsoon flooding creates serious infrastructure and health risks. Terrorism threat remains elevated.', 'Avoid low-lying areas, carry water purification, maintain communication schedule, travel with local guide', 'Security Team Beta'),
      ('Kingston', 'Jamaica', '2026-03-09', 'critical', 'medium', 'low', 'critical', 'high', 'critical', 'high', 85, 'Extreme crime risk combined with hurricane threat. Medical facilities inadequate for serious emergencies.', 'Travel only in groups, avoid downtown after dark, have evacuation plan, carry satellite communicator', 'Security Team Gamma'),
      ('Mexico City', 'Mexico', '2026-03-08', 'high', 'medium', 'medium', 'high', 'medium', 'medium', 'medium', 70, 'Significant kidnapping and cartel violence risk. Express kidnapping targeting tourists increasing.', 'Use only registered transportation, stay in safe neighborhoods, avoid displaying wealth, vary routes', 'Security Team Alpha'),
      ('Istanbul', 'Turkey', '2026-03-07', 'medium', 'medium', 'medium', 'medium', 'low', 'medium', 'low', 55, 'Political tensions affect border regions more than Istanbul proper. Detention of foreign nationals possible.', 'Carry passport at all times, avoid political discussions, stay clear of border areas, monitor news', 'Security Team Beta'),
      ('Dubai', 'UAE', '2026-03-06', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 20, 'Very safe destination with excellent security infrastructure. Strict laws require cultural awareness.', 'Respect local customs, avoid alcohol in public, dress modestly, follow photography restrictions', 'Security Team Alpha'),
      ('Frankfurt', 'Germany', '2026-03-05', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 25, 'Standard European safety profile. Recent cyber attack at airport warrants digital security awareness.', 'Use VPN on public WiFi, avoid airport WiFi for sensitive transactions, keep electronics secure', 'Security Team Beta'),
      ('Singapore', 'Singapore', '2026-03-04', 'low', 'low', 'low', 'low', 'medium', 'low', 'low', 15, 'Extremely safe with excellent infrastructure. Strict drug laws carry severe penalties.', 'Respect all local laws strictly, avoid bringing prescription drugs without documentation, no drug use', 'Security Team Alpha'),
      ('Cancun', 'Mexico', '2026-03-03', 'medium', 'low', 'low', 'high', 'medium', 'medium', 'medium', 58, 'Tourist zone generally safe but surrounding areas have cartel presence. Water safety concerns.', 'Stay within resort zones, use hotel-arranged transport, avoid isolated beaches at night, drink bottled water', 'Security Team Gamma'),
      ('Khartoum', 'Sudan', '2026-03-02', 'critical', 'critical', 'high', 'critical', 'critical', 'medium', 'critical', 95, 'Active war zone with complete breakdown of law and order. No safe areas exist.', 'Immediate evacuation recommended, shelter in place if evacuation impossible, maintain satellite communications', 'Security Team Alpha'),
      ('Florence', 'Italy', '2026-03-01', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 22, 'Very safe European city. Standard pickpocket awareness in tourist areas. Recent train incident was isolated.', 'Standard European travel precautions, use official licensed guides, keep valuables secure', 'Security Team Beta'),
      ('Port-au-Prince', 'Haiti', '2026-02-28', 'critical', 'critical', 'medium', 'critical', 'critical', 'high', 'critical', 92, 'Extremely dangerous environment with gang control of major areas. Active cholera outbreak.', 'Do not travel. If present, seek immediate evacuation through embassy. Carry water purification and medical supplies.', 'Security Team Gamma')
    `);

    // Seed Threat Analyses (15+)
    await client.query(`
      INSERT INTO threat_analyses (title, threat_type, region, country, threat_level, description, potential_impact, affected_areas, mitigation_strategies, intelligence_source, confidence_level, valid_from, valid_until, status) VALUES
      ('ISIS-Inspired Attack Planning - Western Europe', 'Terrorism', 'Europe', 'France', 'critical', 'Intelligence indicates active planning for attacks on public transportation in major European cities.', 'Mass casualties, transportation disruption, widespread panic', 'Paris Metro, London Underground, Berlin U-Bahn', 'Increased surveillance, traveler awareness briefings, avoid peak hours on public transport', 'Five Eyes Intelligence', 'high', '2026-03-01', '2026-06-01', 'active'),
      ('Political Coup Attempt - Thailand', 'Political', 'Southeast Asia', 'Thailand', 'high', 'Military factions positioning for potential coup. Internet blackouts and curfews possible.', 'Communication disruption, curfews, airport closures, violence', 'Bangkok, Chiang Mai, government buildings nationwide', 'Maintain satellite communication, keep 72hr supplies, have multiple exit strategies', 'Regional Intelligence Partners', 'moderate', '2026-03-10', '2026-04-30', 'active'),
      ('Hurricane Season Forecast - Caribbean', 'Natural Disaster', 'Caribbean', 'Jamaica', 'high', 'NOAA predicts above-average hurricane season with 3-5 major hurricanes expected.', 'Infrastructure destruction, flooding, evacuation requirements, flight cancellations', 'Jamaica, Haiti, Cuba, Dominican Republic, Puerto Rico', 'Pre-position evacuation assets, review all Caribbean itineraries, ensure insurance coverage', 'NOAA / National Weather Service', 'confirmed', '2026-06-01', '2026-11-30', 'monitoring'),
      ('Cartel Territory Expansion - Mexico', 'Crime', 'Central America', 'Mexico', 'high', 'Sinaloa cartel expanding operations into previously safe tourist areas in Riviera Maya.', 'Tourist kidnapping, extortion of hotels, violence in resort areas', 'Cancun, Playa del Carmen, Tulum, Merida', 'Review all Mexico itineraries, brief travelers on safety protocols, establish check-in schedules', 'DEA / Mexican Federal Intelligence', 'high', '2026-02-15', '2026-08-15', 'active'),
      ('Ebola Mutation Concern - Central Africa', 'Health', 'Africa', 'DR Congo', 'critical', 'New Ebola variant shows higher transmissibility. WHO considering PHEIC declaration.', 'Potential pandemic, travel restrictions, border closures across Africa', 'Eastern DRC, Rwanda, Uganda, Burundi', 'Suspend all travel to affected region, screen travelers from neighboring countries, prepare quarantine protocols', 'WHO / CDC', 'confirmed', '2026-03-05', '2026-09-05', 'active'),
      ('Cyber Attack Campaign - Global Aviation', 'Cyber', 'Global', 'Germany', 'medium', 'Sophisticated state-sponsored cyber attacks targeting airport systems worldwide.', 'Flight delays, data breaches, booking system failures, passenger data compromise', 'Frankfurt, Heathrow, JFK, Dubai, Singapore airports', 'Advise paper backup of all bookings, avoid airport WiFi, use VPN, keep offline copies of documents', 'Europol / FBI Cyber Division', 'high', '2026-03-01', '2026-06-01', 'active'),
      ('Volcanic Eruption Sequence - Indonesia', 'Natural Disaster', 'Southeast Asia', 'Indonesia', 'high', 'Seismologists warn of potential eruption sequence across Indonesian archipelago.', 'Airport closures, ash clouds, respiratory hazards, tsunami risk', 'Bali, Java, Sumatra, Lombok', 'Distribute masks to travelers, review evacuation routes, have marine evacuation contingency', 'Indonesian Geological Survey', 'moderate', '2026-03-08', '2026-06-08', 'monitoring'),
      ('Sudan Civil War Escalation', 'Armed Conflict', 'Africa', 'Sudan', 'critical', 'Fighting spreading to previously stable areas. Foreign national evacuations becoming impossible.', 'Trapped travelers, embassy closures, humanitarian crisis', 'Khartoum, Darfur, Port Sudan, all major cities', 'Immediate evacuation of all remaining travelers, coordinate with military for extraction', 'UN Security Council / Military Intelligence', 'confirmed', '2026-01-15', '2026-12-31', 'active'),
      ('Monsoon Super-Event - South Asia', 'Natural Disaster', 'South Asia', 'India', 'high', 'Climate models predict exceptionally severe monsoon season with unprecedented rainfall.', 'Catastrophic flooding, infrastructure collapse, disease outbreaks, stranded travelers', 'Mumbai, Delhi, Kolkata, Chennai, Bangladesh', 'Reroute travelers away from flood zones, pre-position evacuation assets, brief on waterborne disease prevention', 'Indian Meteorological Department', 'moderate', '2026-06-01', '2026-10-01', 'monitoring'),
      ('Border Conflict Escalation - Middle East', 'Military', 'Middle East', 'Israel', 'high', 'Military operations intensifying along northern border. Rocket attacks increasing in frequency.', 'Civilian casualties, airport closures, regional destabilization', 'Northern Israel, Southern Lebanon, Golan Heights', 'Avoid northern Israel entirely, know bomb shelter locations, maintain flexible departure plans', 'Israeli Intelligence / UNIFIL', 'confirmed', '2026-02-01', '2026-08-01', 'active'),
      ('Australian Mega-Fire Complex', 'Natural Disaster', 'Oceania', 'Australia', 'medium', 'Multiple fire complexes merging into mega-fire threatening Sydney metropolitan area.', 'Evacuation of suburbs, air quality emergency, transport disruption', 'Sydney, Blue Mountains, Hunter Valley, Wollongong', 'Monitor fire ratings daily, carry P2/N95 masks, know multiple evacuation routes from accommodation', 'NSW Rural Fire Service', 'confirmed', '2026-03-10', '2026-04-30', 'active'),
      ('Tsunami Risk Assessment - Pacific', 'Natural Disaster', 'East Asia', 'Japan', 'medium', 'Increased seismic activity along Pacific Ring of Fire raises tsunami probability.', 'Coastal flooding, infrastructure damage, mass evacuation', 'Japan Pacific Coast, Hawaii, Philippines, Indonesia', 'Review all coastal accommodations, ensure tsunami alert apps installed, brief travelers on evacuation procedures', 'Pacific Tsunami Warning Center', 'moderate', '2026-03-01', '2026-06-01', 'monitoring'),
      ('Gang Violence Surge - Haiti', 'Crime', 'Caribbean', 'Haiti', 'critical', 'Armed gangs now control 80% of Port-au-Prince. Aid workers increasingly targeted.', 'Kidnapping, murder, total lawlessness, humanitarian crisis', 'Port-au-Prince, Artibonite, Nord department', 'Complete travel ban, evacuate any remaining personnel, coordinate with UN peacekeeping', 'UN BINUH / FBI', 'confirmed', '2026-02-01', '2026-12-31', 'active'),
      ('Train Infrastructure Vulnerability - Europe', 'Transportation', 'Europe', 'Italy', 'medium', 'Investigation reveals maintenance failures in high-speed rail infrastructure across Southern Europe.', 'Derailments, service disruptions, passenger injuries', 'Italy, Spain, southern France rail networks', 'Review rail-dependent itineraries, consider air alternatives for critical journeys, monitor service advisories', 'EU Transport Safety Agency', 'moderate', '2026-03-12', '2026-06-12', 'active'),
      ('Diplomatic Detention Risk - Turkey', 'Political', 'Middle East', 'Turkey', 'medium', 'Pattern of arbitrary detention of foreign nationals on vague charges increasing.', 'Traveler detention, consular access delays, extended legal proceedings', 'Istanbul, Ankara, border regions', 'Brief travelers on cultural sensitivity, ensure consular registration, carry embassy contact cards', 'Various Foreign Ministries', 'high', '2026-02-20', '2026-08-20', 'active'),
      ('Cholera Epidemic Expansion - Haiti', 'Health', 'Caribbean', 'Haiti', 'critical', 'Cholera outbreak spreading beyond Port-au-Prince to rural areas. Death toll rising.', 'Epidemic spread to neighboring countries, quarantine requirements', 'All of Haiti, Dominican Republic border region', 'Complete travel ban to Haiti, screen travelers from Dominican Republic, prepare quarantine protocols', 'WHO / PAHO', 'confirmed', '2026-03-01', '2026-09-01', 'active')
    `);

    // Seed Communication Templates (15+)
    await client.query(`
      INSERT INTO communication_templates (name, category, subject, body, severity, channels, language, placeholders, usage_count, status) VALUES
      ('Emergency Evacuation Notice', 'evacuation', 'URGENT: Immediate Evacuation Required - {{destination}}', 'Dear {{traveler_name}},\n\nDue to {{threat_type}} in {{destination}}, immediate evacuation is required.\n\nEvacuation Point: {{evacuation_point}}\nTransportation: {{transport_details}}\nDeadline: {{deadline}}\n\nPlease proceed immediately to the evacuation point. Contact our 24/7 hotline at {{hotline_number}} if you need assistance.\n\nStay safe,\nTravel Security Operations', 'critical', 'email,sms,push', 'English', 'traveler_name, destination, threat_type, evacuation_point, transport_details, deadline, hotline_number', 12, 'active'),
      ('Severe Weather Alert', 'weather', 'Weather Alert: {{weather_type}} Warning for {{destination}}', 'Dear {{traveler_name}},\n\nA {{weather_type}} warning has been issued for {{destination}} effective {{start_time}}.\n\nExpected Impact:\n{{impact_details}}\n\nRecommended Actions:\n- Stay indoors at your accommodation\n- Stock up on water and non-perishable food\n- Keep your phone charged\n- Monitor local news channels\n\nYour accommodation: {{hotel_name}}\nLocal emergency number: {{emergency_number}}\n\nWe are monitoring the situation closely.\n\nTravel Security Operations', 'high', 'email,sms', 'English', 'traveler_name, destination, weather_type, start_time, impact_details, hotel_name, emergency_number', 28, 'active'),
      ('Security Incident Alert', 'security', 'Security Alert: {{incident_type}} in {{location}}', 'Dear {{traveler_name}},\n\nWe are aware of a {{incident_type}} in {{location}} near your current position.\n\nDetails: {{incident_details}}\nThreat Level: {{severity}}\n\nImmediate Actions:\n1. Move to a secure location\n2. Avoid the area around {{affected_area}}\n3. Keep your phone accessible\n4. Follow instructions from local authorities\n\nOur security team is monitoring the situation. We will update you as more information becomes available.\n\nEmergency Contact: {{emergency_contact}}\n\nTravel Security Operations', 'high', 'email,sms,push', 'English', 'traveler_name, incident_type, location, incident_details, severity, affected_area, emergency_contact', 45, 'active'),
      ('Health Advisory', 'health', 'Health Advisory: {{disease}} Risk in {{destination}}', 'Dear {{traveler_name}},\n\nA health advisory has been issued regarding {{disease}} in {{destination}}.\n\nRisk Level: {{risk_level}}\nAffected Areas: {{affected_areas}}\n\nPrecautionary Measures:\n{{precautions}}\n\nNearest Medical Facility: {{hospital_name}}\nHospital Contact: {{hospital_phone}}\n\nIf you experience any symptoms ({{symptoms}}), seek immediate medical attention.\n\nTravel Security Operations', 'medium', 'email', 'English', 'traveler_name, disease, destination, risk_level, affected_areas, precautions, hospital_name, hospital_phone, symptoms', 15, 'active'),
      ('Daily Check-In Request', 'check_in', 'Daily Check-In: Please Confirm Your Status', 'Dear {{traveler_name}},\n\nThis is your daily safety check-in for {{date}}.\n\nYour current trip: {{destination}} ({{trip_dates}})\n\nPlease reply with:\n✓ SAFE - All is well\n⚠ CONCERN - Need non-urgent assistance\n🆘 EMERGENCY - Need immediate help\n\nIf we do not hear from you by {{deadline}}, our security team will attempt to reach you.\n\nTravel Security Operations', 'low', 'email,sms', 'English', 'traveler_name, date, destination, trip_dates, deadline', 350, 'active'),
      ('Travel Advisory Update', 'general', 'Updated Travel Advisory: {{country}}', 'Dear {{traveler_name}},\n\nThe travel advisory for {{country}} has been updated.\n\nPrevious Level: {{previous_level}}\nNew Level: {{new_level}}\nReason: {{reason}}\n\nKey Changes:\n{{changes}}\n\nOur Recommendation: {{recommendation}}\n\nPlease review the full advisory and contact us if you have questions about your upcoming trip.\n\nTravel Security Operations', 'medium', 'email', 'English', 'traveler_name, country, previous_level, new_level, reason, changes, recommendation', 67, 'active'),
      ('Emergency Contact Card', 'emergency', 'Your Emergency Contact Information - {{destination}}', 'Dear {{traveler_name}},\n\nHere are your emergency contacts for {{destination}}:\n\n🏥 Medical Emergency: {{medical_number}}\n🚔 Police: {{police_number}}\n🏛 Embassy: {{embassy_number}}\n📞 Our 24/7 Hotline: {{hotline}}\n\nYour Trip ID: {{trip_id}}\nHotel: {{hotel_name}} ({{hotel_phone}})\n\nSave these numbers in your phone before departure.\n\nTravel Security Operations', 'low', 'email', 'English', 'traveler_name, destination, medical_number, police_number, embassy_number, hotline, trip_id, hotel_name, hotel_phone', 200, 'active'),
      ('Evacuation Drill Notification', 'evacuation', 'Scheduled Evacuation Drill - {{destination}}', 'Dear {{traveler_name}},\n\nA mandatory evacuation drill is scheduled for {{date}} at {{time}}.\n\nMeeting Point: {{meeting_point}}\nExpected Duration: {{duration}}\n\nPlease familiarize yourself with the evacuation routes posted in your accommodation.\n\nTravel Security Operations', 'low', 'email', 'English', 'traveler_name, destination, date, time, meeting_point, duration', 8, 'active'),
      ('Protest/Demonstration Warning', 'security', 'Demonstration Alert: Avoid {{area}} in {{city}}', 'Dear {{traveler_name}},\n\nA {{protest_type}} is planned for {{date}} in {{area}}, {{city}}.\n\nExpected Size: {{expected_size}}\nTime: {{start_time}} - {{end_time}}\n\nAreas to Avoid:\n{{avoid_areas}}\n\nAlternative Routes:\n{{alt_routes}}\n\nDemonstrations can escalate without warning. Please maintain distance and avoid photographing participants.\n\nTravel Security Operations', 'medium', 'email,sms', 'English', 'traveler_name, protest_type, date, area, city, expected_size, start_time, end_time, avoid_areas, alt_routes', 23, 'active'),
      ('Flight Disruption Notice', 'general', 'Flight Disruption: {{flight_number}} - {{route}}', 'Dear {{traveler_name}},\n\nYour flight {{flight_number}} ({{route}}) has been {{disruption_type}}.\n\nReason: {{reason}}\nNew Status: {{new_status}}\n\nAction Required:\n{{action_required}}\n\nAlternative Options:\n{{alternatives}}\n\nOur team is working on rebooking. We will update you within {{update_time}}.\n\nTravel Security Operations', 'medium', 'email,sms', 'English', 'traveler_name, flight_number, route, disruption_type, reason, new_status, action_required, alternatives, update_time', 89, 'active'),
      ('Kidnapping Prevention Briefing', 'security', 'Security Briefing: Personal Safety in {{destination}}', 'Dear {{traveler_name}},\n\nBased on current conditions in {{destination}}, please review these personal safety guidelines:\n\n1. Transportation: Use only pre-arranged or hotel-verified transportation\n2. Communication: Share your daily itinerary with our ops center\n3. Awareness: Vary your routes and schedules\n4. Valuables: Minimize visible jewelry and electronics\n5. Emergency: Memorize the duress code: {{duress_code}}\n\nCheck-in Schedule: {{checkin_times}}\nPanic Button App: Download TravelSafe from {{app_link}}\n\nTravel Security Operations', 'high', 'email', 'English', 'traveler_name, destination, duress_code, checkin_times, app_link', 34, 'active'),
      ('Natural Disaster Preparation', 'weather', 'Preparation Guide: {{disaster_type}} Season in {{destination}}', 'Dear {{traveler_name}},\n\nYou are traveling to {{destination}} during {{disaster_type}} season ({{season_dates}}).\n\nPreparation Checklist:\n□ Download local emergency alert apps\n□ Locate nearest evacuation shelter\n□ Prepare 72-hour emergency kit\n□ Save offline maps of your area\n□ Charge all devices and portable chargers\n□ Keep important documents in waterproof bag\n\nEvacuation Assembly Point: {{assembly_point}}\n\nTravel Security Operations', 'medium', 'email', 'English', 'traveler_name, destination, disaster_type, season_dates, assembly_point', 56, 'active'),
      ('Post-Incident Follow-Up', 'general', 'Follow-Up: {{incident_type}} in {{location}} on {{date}}', 'Dear {{traveler_name}},\n\nFollowing the {{incident_type}} in {{location}} on {{date}}, we wanted to check in.\n\nCurrent Status: {{current_status}}\nAll Clear: {{all_clear}}\n\nSupport Available:\n- Counseling: {{counseling_contact}}\n- Insurance Claims: {{insurance_contact}}\n- Medical Follow-up: {{medical_contact}}\n\nPlease do not hesitate to reach out if you need any additional support.\n\nTravel Security Operations', 'low', 'email', 'English', 'traveler_name, incident_type, location, date, current_status, all_clear, counseling_contact, insurance_contact, medical_contact', 18, 'active'),
      ('VIP Traveler Security Brief', 'security', 'Confidential Security Briefing: {{destination}} Trip', 'Dear {{traveler_name}},\n\nClassified: For your eyes only\n\nYour upcoming trip to {{destination}} ({{trip_dates}}) requires enhanced security measures.\n\nSecurity Detail: {{security_detail}}\nSecure Transportation: {{transport_details}}\nSafe Room Location: {{safe_room}}\nCommunication Protocol: {{comm_protocol}}\n\nDaily Itinerary Review: {{review_time}}\nAdvance Team Contact: {{advance_contact}}\n\nThis briefing is confidential. Do not forward.\n\nTravel Security Operations', 'critical', 'email', 'English', 'traveler_name, destination, trip_dates, security_detail, transport_details, safe_room, comm_protocol, review_time, advance_contact', 5, 'active'),
      ('Border Closure Notification', 'emergency', 'URGENT: Border Closure - {{border}} Effective {{effective_date}}', 'Dear {{traveler_name}},\n\nThe {{border}} border has been closed effective {{effective_date}} due to {{reason}}.\n\nImpact on Your Trip:\n{{trip_impact}}\n\nAlternative Exit Routes:\n{{alt_routes}}\n\nEmbassy Coordination:\n{{embassy_info}}\n\nPlease contact our operations center immediately at {{ops_number}} to discuss your options.\n\nTravel Security Operations', 'critical', 'email,sms,push', 'English', 'traveler_name, border, effective_date, reason, trip_impact, alt_routes, embassy_info, ops_number', 3, 'active')
    `);

    // Seed Geofencing Zones (15+)
    await client.query(`
      INSERT INTO geofencing_zones (name, zone_type, country, region, center_lat, center_lng, radius_km, description, alert_message, severity, active_travelers, status) VALUES
      ('Paris Metro High-Risk Zone', 'danger', 'France', 'Europe', 48.8566, 2.3522, 2.5, 'Central Paris metro stations identified as potential terrorism targets', 'You are entering a high-risk zone near Paris metro. Exercise extreme caution.', 'critical', 15, 'active'),
      ('Bangkok Protest Zone', 'restricted', 'Thailand', 'Southeast Asia', 13.7500, 100.4913, 3.0, 'Government district where protests are concentrated', 'Warning: Active protest zone. Avoid this area if possible.', 'high', 8, 'active'),
      ('Mount Agung Exclusion Zone', 'danger', 'Indonesia', 'Southeast Asia', -8.3431, 115.5070, 10.0, 'Volcanic exclusion zone around Mount Agung crater', 'DANGER: You are entering the volcanic exclusion zone. Evacuate immediately.', 'critical', 0, 'active'),
      ('Cancun Safe Tourist Zone', 'safe', 'Mexico', 'Central America', 21.1619, -86.8515, 5.0, 'Hotel zone and main tourist corridor with enhanced security', 'You are in the Cancun safe tourist zone. Hotel zone security is active.', 'low', 45, 'active'),
      ('Khartoum Conflict Zone', 'danger', 'Sudan', 'Africa', 15.5007, 32.5599, 50.0, 'Active combat zone covering greater Khartoum metropolitan area', 'EXTREME DANGER: Active combat zone. Seek immediate shelter and contact operations.', 'critical', 4, 'active'),
      ('Mumbai Flood Zone', 'danger', 'India', 'South Asia', 19.0760, 72.8777, 8.0, 'Low-lying areas of Mumbai prone to monsoon flooding', 'Flood warning zone. Move to higher ground if water levels are rising.', 'high', 12, 'active'),
      ('Tokyo Tsunami Evacuation Zone', 'evacuation', 'Japan', 'East Asia', 35.6545, 139.7975, 3.0, 'Tokyo Bay waterfront area designated for tsunami evacuation', 'Tsunami evacuation zone. If warning sounds, move to designated high ground immediately.', 'high', 20, 'active'),
      ('Mexico City Kidnapping Hotspot', 'danger', 'Mexico', 'Central America', 19.4440, -99.1310, 4.0, 'Tepito and surrounding neighborhoods with highest kidnapping risk', 'HIGH RISK: Kidnapping hotspot area. Leave this area immediately and use verified transportation.', 'critical', 3, 'active'),
      ('Sydney Wildfire Perimeter', 'danger', 'Australia', 'Oceania', -33.7500, 150.7000, 25.0, 'Blue Mountains wildfire affected area with poor air quality', 'Wildfire zone. Air quality hazardous. Wear P2 mask and prepare for possible evacuation.', 'high', 8, 'active'),
      ('Dubai Safe Zone - City Center', 'safe', 'UAE', 'Middle East', 25.2048, 55.2708, 15.0, 'Dubai city center with comprehensive security coverage', 'You are in Dubai safe zone. Excellent security infrastructure surrounds you.', 'low', 15, 'active'),
      ('Istanbul Border Security Zone', 'restricted', 'Turkey', 'Middle East', 39.9334, 32.8597, 5.0, 'Government and military areas with restricted access', 'Restricted area near government buildings. Photography prohibited. Carry ID.', 'medium', 5, 'active'),
      ('Port-au-Prince Gang Territory', 'danger', 'Haiti', 'Caribbean', 18.5944, -72.3074, 15.0, 'Areas under gang control - extremely dangerous', 'EXTREME DANGER: Gang-controlled territory. Do not proceed. Contact operations for evacuation.', 'critical', 2, 'active'),
      ('Singapore Changi Airport Safe Zone', 'safe', 'Singapore', 'Southeast Asia', 1.3644, 103.9915, 3.0, 'Changi Airport and surrounding area with excellent security', 'Singapore Changi Airport safe zone. World-class security and facilities available.', 'low', 8, 'active'),
      ('Israel Northern Border Zone', 'danger', 'Israel', 'Middle East', 33.2774, 35.2043, 20.0, 'Northern border region with active military operations', 'DANGER: Active military zone. Rocket attacks possible. Move south immediately.', 'critical', 3, 'active'),
      ('Frankfurt Airport Monitoring Zone', 'monitoring', 'Germany', 'Europe', 50.0379, 8.5622, 5.0, 'Frankfurt airport area under enhanced monitoring after cyber attack', 'Enhanced monitoring zone. Report suspicious activity. Avoid public WiFi.', 'medium', 45, 'active'),
      ('Jamaica Hurricane Evacuation Zone', 'evacuation', 'Jamaica', 'Caribbean', 18.1096, -77.2975, 30.0, 'Coastal areas requiring evacuation during hurricane warnings', 'Hurricane evacuation zone. When warning is issued, move to designated inland shelters.', 'high', 25, 'active')
    `);

    console.log('Database seeded successfully with all data!');
    client.release();
    await pool.end();
  } catch (err) {
    console.error('Error seeding database:', err.message);
    process.exit(1);
  }
};

seed();
